### ISSUE TITLE
Exits randomly while editing inside of try catch statement

### ISSUE THREAD

**Issue by ErikReider** [vala-lang/vala-language-server#250]
**Describe the bug**
Using the completion menu (nvim-cmp in this case) sometimes crashes the LSP. It also crashes in VSCode. Here's the output from VSCode: [Gist](https://gist.github.com/ErikReider/dc47766423bb8bee6360c3ad1d99388d)

**Software**
OS and version (e.g. Ubuntu 20.04): Arch
Code editor (e.g. VSCode): NeoVim
Vala Language Server: vala-language-server-git 0.48.4.r44.484465d6-1
Vala version: Vala 0.56.1

1. Create a basic vala project through meson (`meson init --language vala`)
2. add "dependency('gio-2.0', version: '>= 2.50')" to `dependencies` in `meson.build`
3. Replace all lines in the vala file with:
``` vala
void main (string[] args) {
    try {
        File e = File.new_build_filename (string first_element, ...)
    } catch (Error e) {
        stderr.printf ("ERROR: %s\n", e.message);
    }
}
```
5. The LSP should crash. If not, try restarting the editor and open the file again

**Comment by Prince781** [comment]
As this part of the output indicates:

```
(vala-language-server:51616): vls-ERROR **: 12:21:33.263: parser infinite loop detected! (seen "syntax error, expected identifier" @ vala_test.vala:3.65-3.67 at least 100 times)
note: please report this bug with the source code that causes this error at https://gitlab.gnome.org/GNOME/vala
```

This is actually an issue with the parser in the Vala compiler (you will notice this if you try to compile it with `valac`). Therefore this is an upstream issue. Please go to https://gitlab.gnome.org/GNOME/vala and report a parser bug with this source code. VLS will automatically abort because otherwise it will use up all the memory in your system.
